### PR TITLE
Swap mimetype gem for marcel

### PR DESCRIPTION
**Pull request by xcoan-conga**
@wip

### CODE REVIEW

**Comment by wnovak-conga** [comment]
I think you want the base to be the forked repo, no?

**Comment by xcoan-conga** [comment]
@wnovak-conga tinderbox hosts the original, but I wasn't sure if we wanted to update that moving forward or just work off this is a new fork.
I suppose we can do either.

**Comment by wnovak-conga** [comment]
I mean, Conga owns it. So in my opinion it'd be better to keep it owned by Conga since the original isn't going to work moving forward anyway.

**Comment by xcoan-conga** [comment]
see https://github.com/TinderBox/dynamics_crm/pull/67

**Pull request closed without merging**
